RegisterNetEvent('rabbit-score:sv:Submit')
AddEventHandler('rabbit-score:sv:Submit', function(data)
  TriggerClientEvent('rabbit-score:cl:Submit', -1, data)
end)

TriggerEvent("es:addGroupCommand", Config.Command, "admin", function(source, args, rawCommand)
	TriggerClientEvent('rabbit-score:cl:openmenu', source)
end, function(source, args, rawCommand)
	TriggerClientEvent("mythic_notify:client:SendAlert", source, { type = "error", text = "คุณไม่มีสิทธิ์ แค่คิดรักเธอก็ผิดแล้ว" })
end)